name = "workers-tunnel"
main = "build/worker/shim.mjs"
compatibility_date = "2026-03-09"
account_id = "54211bf1c63ae3a5729dabd4bf94aa2b"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
USER_ID = "c55ba35f-12f6-436e-a451-4ce982c4ec1c" # your uuid
PROXY_IP = "proxyip.fxxk.dedyn.io" # proxyip.fxxk.dedyn.io
FALLBACK_SITE = "" # https://httpbin.org/status/404
SHOW_URI = "true" # show vless uri in /UUID path
